# Generated by Django 4.1.7 on 2023-09-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0002_alter_profile_photo'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='extended_user.profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='info',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
