# Generated by Django 4.1.7 on 2023-03-31 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка мероприятия со стороны студента')),
                ('estimation', models.IntegerField(blank=True, null=True, verbose_name='Оценка работы студента')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='event.event', verbose_name='Мероприятие')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='extended_user.profile', verbose_name='Студент')),
            ],
        ),
    ]
