# Generated by Django 4.1.7 on 2023-03-31 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('info', models.CharField(max_length=5000, verbose_name='Описание')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('time_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('registration_start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Начало регистрации')),
                ('registration_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец регистрации')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Прикрепленный файл')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='extended_user.profile', verbose_name='Организаторы')),
            ],
        ),
    ]
