# Generated by Django 4.1.7 on 2023-03-31 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(related_name='organizers', to='extended_user.profile', verbose_name='Организаторы мероприя'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='author', to='extended_user.profile', verbose_name='Создатель'),
        ),
    ]
