# Generated by Django 4.1.7 on 2023-03-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extended_user', '0001_initial'),
        ('event', '0002_event_organizers_alter_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(related_name='organizers', to='extended_user.profile', verbose_name='Организаторы'),
        ),
    ]
