# Generated by Django 4.1.7 on 2023-09-03 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_user', '0002_alter_profile_photo'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(verbose_name='Описание')),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('time_edit', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Прикрепленный файл')),
                ('mark', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий от проверяющего')),
                ('classes_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='homeworks_by_classes', to='classes.class', verbose_name='Занятие')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='homeworks_by_student', to='extended_user.profile', verbose_name='Студент')),
            ],
        ),
    ]
