# Generated by Django 4.1.7 on 2023-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание комментария')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_edit', models.DateTimeField(auto_now=True, verbose_name='Дата измения')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('time_create',),
            },
        ),
    ]
